version: '2'

services:
    caliper:
        container_name: caliper
        image: hyperledger/caliper:0.5.0
        command: launch manager
        environment:
        - CALIPER_BIND_SUT=ethereum:1.3
        - CALIPER_BENCHCONFIG=benchmarks/scenario/simple/config.yaml
        - CALIPER_NETWORKCONFIG=networks/ethereum/test-network.json
        volumes:
        - ~/caliper-benchmarks:/hyperledger/caliper/workspace
